### ISSUE TITLE
Storage layout allows overwriting balance values with allowances

### ISSUE THREAD

**Issue by veox** [benjaminion/LLL_erc20#1]
The storage layout, as described on [this line](https://github.com/benjaminion/LLL_erc20/blob/b2a333d358ff01d4773bbb0182a7da4ea6faa9f6/erc20.lll#L60), is not particularly safe.

For ref:

``` lisp
 ;; Allowances are stored at s[owner_addr + keccak256(spender_addr)]
  ;;   We use a crypto function here to avoid any situation where
  ;;   approve(me, spender) can be abused to do approve(target, me).
  (def 'allowance (owner spender)
    (seq
      (mstore mem-keccak spender)
      (add owner (keccak256 mem-keccak 0x20))))
```

-----

Consider an `owner` address with a lot of zeros up-front, e.g. eight:

`0x 00000000 XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX`

Consider then that `keccak(spender)` will be of form:

`0x ZZZZZZZZ YYYYYYYY YYYYYYYY YYYYYYYY YYYYYYYY`

If, at this point, the following is true (intuitively: 25% probability):

```
0x 00000000 XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX +
0x 00000000 YYYYYYYY YYYYYYYY YYYYYYYY YYYYYYYY <
0x 00000001 00000000 00000000 00000000 00000000
```

Then it is possible to write to storage locations associated with _balances_ (of addresses starting with `0xZZZZZZZZ`) when setting _allowances_ from address `0x[0XXXX]`.

This is exacerbated by the fact that setting an allowance does not reduce an account's balance. Effectively, a large portion (intuitively 25% of addresses starting with `0xZZZZZZZZ`) of accounts can be given balances "out of thin air".

I don't think this can be easily gamed to extract value, as that would amount to a [preimage attack](https://en.wikipedia.org/wiki/Preimage_attack); however, it does seem possible to wreak havoc.

At the root of the issue is: the lack of guarantee for: non-overlap of storage locations.

-----

The particular numbers - 8 zeros up-front, 25% - can be different; reducing the number of zeros also reduces the "location-space" that can be written in a bogus manner, but is also easier on computation.

**Comment by veox** [comment]
Regarding the feasibility of getting an address with a specific prefix: I was able to generate such addresses with up to 8 pre-determined hex characters (i.e. 4 bytes), using un-optimised JavaScript-based [`VanityEth`](https://github.com/MyEtherWallet/VanityEth) on a 5-year-old 6-core consumer processor, running the process in low-priority, within a few days (each).

In other words, this is trivial.

**Comment by veox** [comment]
For ref: this has come up in a [brainstorm session](https://gitlab.com/veox/oobiqoo/blob/master/docs/2017-11-28-brainstorm-on-token-storage-layout.md) for an application where - I'm reasonably sure - implementing the token in LLL would be desirable.

-----

The solution to this issue could be rather simple: for example, set the top-most byte of that storage location to something other than `0x00`. In the link above, that's `0x01`.

In might be prudent, though, to use more of unallocated storage in addition to the above; e.g. by shifting the `owner` address left; or hashing both values together, and using as many bytes of the result as possible (I'm thinking 30-31).

**Comment by veox** [comment]
I probably _could_ demonstrate this with a purpose-built ~~exploit~~ piece of software, if I had the token... ;)

But that would take quite some time, and I hope an overly-verbose description would be sufficient. :)

**Comment by veox** [comment]
I've also found the token [in the `ethereum/solidity` repo](https://github.com/ethereum/solidity/blob/e45e95f578ee51788bc4d7d588c84e2cc3060420/test/contracts/LLL_ERC20.cpp#L102), with a slightly different implementation.

**Comment by benjaminion** [comment]
@veox  - Many thanks for this, and apologies for the slow reply. I must have missed a notification from GitHub somewhere... Anyway, @zigguratt gave me the heads up.

Looks very neat! I'll have a proper look at the weekend.

The version in the Solidity repo is just a "real-life" parser test for the compiler, so the implementation details are not very significant. It does suffer from a (more severe) bug in just this place as you spotted.

**Comment by benjaminion** [comment]
Having slept on this, I'm feeling a lot more comfortable that the laws of probability save us from any significant harm.

To summarise what I understand you to be saying:

  * Account balances are stored by `owner_address`.
  * Approvals are stored by `owner_address + keccak256(spender_address)`.
  * When `keccak256(spender_address)` is small enough (or large enough, due to overflow), it's possible for allowances and balances to overwrite each other.  

I agree that this does seem to be the case, but I think the probabilities are vastly lower than you are suggesting.

For this to be triggered, the `spender_address` needs to hash to a 256 bit number with 12 leading zero bytes. This means you need to do O(2^96) work even before we reach the situation you outline in the first comment, in addition to finding any further zero bytes.  O(2^96) work is equivalent to creating an Ethereum address with 24 leading pre-determined hex digits - decidedly non-trivial.

In other words, even finding a `spender` address such that `keccak256(spender)` has the following form is fabulously hard, never mind making some of the Zs zero as well:

    0x ZZZZZZZZ YYYYYYYY YYYYYYYY YYYYYYYY YYYYYYYY

In addition, since I check address lengths on input (I knew I did this for a reason!), the space of possible `spender` addresses that is available is only 160 bits long (not the full 256 bits). So, only on average 2^(160-96) = 2^64 addresses out of the whole address space have the property required, which again severely limits any damage this can cause. (I.e. "only" one in every 2^96 account balances could ever be corrupted by this issue).

As you say, any actual attack would require a preimage, and also be subject to the constraints in the last paragraph, so is utterly impratical.

Nonetheless, this is a genuine issue - it's not good to have even a small possibility of random balances being assigned even if they are not accessible. As for fixing it, probably the only way to guarantee storage space separation is to ensure that one of the higher-order bits (> bit 159) is set for allowance storage. This reduces the available storage space for allowances by a factor of two, but there's still quite a lot of it.

Interestingly, since we are trying to index two 160 bit addresses within a single 256 bit address space, there is also a possibility of allowances clashing - one [owner, spender] pair is valid for 2^64 - 1 other [owner, spender] pairs on average. Again the laws of probability save us. Using the fix in the last paragraph reduces the 256-bit space to 255 bits, doubling the chance of an issue here. But this is so minuscule as to be of no practical interest.

I'll work on a fix along these lines, but I don't think there is any practical issue for any contracts already deployed (unless I've misunderstood something, in which case, please get back to me!).

**Comment by veox** [comment]
I'm now afraid that you're correct, and this was an utter waste of your time. Sorry. :(

Most importantly:

> For this to be triggered, the `spender_address` needs to hash to a 256 bit number with 12 leading zero bytes.

I have conveniently forgotten that the result of a `keccak256` will be 32 bytes, and not 20. This has actually shown in [this follow-up comment](https://github.com/benjaminion/LLL_erc20/issues/1#issuecomment-348520430) of mine:

> The solution to this issue could be rather simple: for example, set the top-most byte of that storage location to something other than `0x00`. In the link above, that's `0x01`.
> 
> In might be prudent, though, to use more of unallocated storage in addition to the above; e.g. by shifting the `owner` address left; or hashing both values together, and using as many bytes of the result as possible (I'm thinking 30-31).

-----

It was perhaps because I was entrenched in thinking about my own application-specific storage layout, where making classes of values (balances, allowances, others) map to specific non-overlapping storage ranges seemed useful; and then erroneously applying such thinking to _this_ particular contract also, where there's literally nothing else stored _but_ balances and allowances, - so it might be acceptable to map one over the _entire_ address space (which, again, I conveniently ignored), and let improbability handle the rest.

**Comment by veox** [comment]
However, if you're going to implement

> the only way to guarantee storage space separation is to ensure that one of the higher-order bits (> bit 159) is set for allowance storage

that would IMO be an unprecedented guarantee of "correct" program behaviour, at least as far as ERC20 implementations go. :)

(This might greatly simplify formal proof, if anyone needed a target for such an endeavour.)

**Comment by benjaminion** [comment]
Hi @veox.

I'm unsure of the best approach here. I think the current approach to storage layout is reasonable, and I don't think there is urgency to change things. If the LLL coin were worth billions I might think about it harder 😀 

The issue is that the storage address space is "only" 256 bits large and it is already overloaded. Into these 256 bits, we are trying to cram:

  1. allowances: a 320-bit allowance address space (2^160 * 2^160 possible allowances), alongside
  2. balances: a much smaller 160-bit address space.

These just don't fit in, so anything will be a compromise. This is a fundamental EVM limitation and would apply equally to LLL or Solidity ERC20 implementations.

We can remove any clash between allowances & balances as discussed above, but that then means that the 320 bits of allowance are now crammed into 255 bits, making issue 1 worse. This may be preferable since allowances are likely less exploitable than balances, but it's not entirely clear to me what is best.

The only real way to solve this would be to implement something like lists in storage to handle the allowances for each account, but this would be horribly expensive in gas terms, at least any implementation I can think of.
